[package]
name = "ckb-mmr-wasm"
version = "0.1.0"
edition = "2021"

[lib]
name = "ckb_mmr_wasm"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "ckb-mmr-wasm"
path = "src/main.rs"

[dependencies]
ckb-merkle-mountain-range = "0.5.0"
hex = "0.4.3"
wasm-bindgen = "0.2.99"
js-sys = "0.3"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


